[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
aa_factory = "8YWxzcPJMwGnaG3CUcxxV2PThbARj2LSAGnPrdB4mYDk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
